version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: franciadb
      MYSQL_USER: root
      MYSQL_PASSWORD: contraseña_mysql
    ports:
      - "3306:3306"
    networks:
      - backend_network

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
